Drone:
  Name: drone-01
  Id: 1
  CameraTilt: 15
  FOV: 80
  FrameSize:
    - 640
    - 480
  CameraMatrix:
    rows: 3
    cols: 3
    type: 5
    data:
      - 903.4967710428723
      - 0
      - 318.0171624577062
      - 0
      - 903.4967710428723
      - 103.3992904495036
      - 0
      - 0
      - 1
  DistortionCoefficients:
    rows: 5
    cols: 1
    type: 5
    data:
      - 0.4872980520696654
      - -1.144102834824387
      - -0.1049593754864662
      - 0.002789408258186383
      - 2.415463706902218
Communications:
  BrainHost: localhost
  BrainPort: 11500
  BroadcastPort: 11501
  AdvertisementLapse: 5000
  CommunicationPort: 11502
  PingTimeout: 10000
  PingLapse: 5000
  PingEnabled: false
Debugging:
  VisualDebugEnabled: true
  OutputHudVideoEnabled: true
  OutputRawVideoEnabled: false
  OutputPath: ""
  RealTimeVideoOutputEnabled: false
Body:
  SleepDelay: 0
  Start: true
  Hal: Dummy
  ParentOnFork: true
  TestToExecute: "OpticalFlowObstacleAvoidance"
Brain:
  Start: true
