// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: advertisement.proto

#ifndef PROTOBUF_advertisement_2eproto_INCLUDED
#define PROTOBUF_advertisement_2eproto_INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_advertisement_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsAdvertisementImpl();
void InitDefaultsAdvertisement();
inline void InitDefaults() {
  InitDefaultsAdvertisement();
}
}  // namespace protobuf_advertisement_2eproto
class Advertisement;
class AdvertisementDefaultTypeInternal;
extern AdvertisementDefaultTypeInternal _Advertisement_default_instance_;
namespace google {
namespace protobuf {
template<> ::Advertisement* Arena::Create< ::Advertisement>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Advertisement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Advertisement) */ {
 public:
  Advertisement();
  virtual ~Advertisement();

  Advertisement(const Advertisement& from);

  inline Advertisement& operator=(const Advertisement& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Advertisement(Advertisement&& from) noexcept
    : Advertisement() {
    *this = ::std::move(from);
  }

  inline Advertisement& operator=(Advertisement&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Advertisement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Advertisement* internal_default_instance() {
    return reinterpret_cast<const Advertisement*>(
               &_Advertisement_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Advertisement* other);
  friend void swap(Advertisement& a, Advertisement& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Advertisement* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Advertisement>(NULL);
  }

  Advertisement* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Advertisement>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Advertisement& from);
  void MergeFrom(const Advertisement& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Advertisement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // fixed32 ip = 1;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  ::google::protobuf::uint32 ip() const;
  void set_ip(::google::protobuf::uint32 value);

  // uint32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Advertisement)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 ip_;
  ::google::protobuf::uint32 port_;
  mutable int _cached_size_;
  friend struct ::protobuf_advertisement_2eproto::TableStruct;
  friend void ::protobuf_advertisement_2eproto::InitDefaultsAdvertisementImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Advertisement

// fixed32 ip = 1;
inline void Advertisement::clear_ip() {
  ip_ = 0u;
}
inline ::google::protobuf::uint32 Advertisement::ip() const {
  // @@protoc_insertion_point(field_get:Advertisement.ip)
  return ip_;
}
inline void Advertisement::set_ip(::google::protobuf::uint32 value) {
  
  ip_ = value;
  // @@protoc_insertion_point(field_set:Advertisement.ip)
}

// uint32 port = 2;
inline void Advertisement::clear_port() {
  port_ = 0u;
}
inline ::google::protobuf::uint32 Advertisement::port() const {
  // @@protoc_insertion_point(field_get:Advertisement.port)
  return port_;
}
inline void Advertisement::set_port(::google::protobuf::uint32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:Advertisement.port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_advertisement_2eproto_INCLUDED
