// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronestate.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dronestate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class DroneStateDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<DroneState> {
} _DroneState_default_instance_;

namespace protobuf_dronestate_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DroneState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DroneState, ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DroneState, port_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DroneState, drone_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DroneState, seq_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DroneState, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DroneState, curren_task_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(DroneState)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_DroneState_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "dronestate.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _DroneState_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _DroneState_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\020dronestate.proto\"\332\001\n\nDroneState\022\n\n\002ip\030"
      "\001 \001(\007\022\014\n\004port\030\002 \001(\r\022\020\n\010drone_id\030\003 \001(\r\022\017\n"
      "\007seq_num\030\004 \001(\003\022\014\n\004name\030\005 \001(\t\022,\n\013curren_t"
      "ask\030\006 \001(\0162\027.DroneState.CurrentTask\"S\n\013Cu"
      "rrentTask\022\r\n\tINNACTIVE\020\000\022\r\n\tPATROLING\020\001\022"
      "\r\n\tFOLLOWING\020\002\022\t\n\005ALERT\020\003\022\014\n\010CHARGING\020\004b"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 247);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dronestate.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_dronestate_2eproto

const ::google::protobuf::EnumDescriptor* DroneState_CurrentTask_descriptor() {
  protobuf_dronestate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_dronestate_2eproto::file_level_enum_descriptors[0];
}
bool DroneState_CurrentTask_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const DroneState_CurrentTask DroneState::INNACTIVE;
const DroneState_CurrentTask DroneState::PATROLING;
const DroneState_CurrentTask DroneState::FOLLOWING;
const DroneState_CurrentTask DroneState::ALERT;
const DroneState_CurrentTask DroneState::CHARGING;
const DroneState_CurrentTask DroneState::CurrentTask_MIN;
const DroneState_CurrentTask DroneState::CurrentTask_MAX;
const int DroneState::CurrentTask_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DroneState::kIpFieldNumber;
const int DroneState::kPortFieldNumber;
const int DroneState::kDroneIdFieldNumber;
const int DroneState::kSeqNumFieldNumber;
const int DroneState::kNameFieldNumber;
const int DroneState::kCurrenTaskFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DroneState::DroneState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_dronestate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:DroneState)
}
DroneState::DroneState(const DroneState& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&ip_, &from.ip_,
    reinterpret_cast<char*>(&curren_task_) -
    reinterpret_cast<char*>(&ip_) + sizeof(curren_task_));
  // @@protoc_insertion_point(copy_constructor:DroneState)
}

void DroneState::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&ip_, 0, reinterpret_cast<char*>(&curren_task_) -
    reinterpret_cast<char*>(&ip_) + sizeof(curren_task_));
  _cached_size_ = 0;
}

DroneState::~DroneState() {
  // @@protoc_insertion_point(destructor:DroneState)
  SharedDtor();
}

void DroneState::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DroneState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DroneState::descriptor() {
  protobuf_dronestate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_dronestate_2eproto::file_level_metadata[0].descriptor;
}

const DroneState& DroneState::default_instance() {
  protobuf_dronestate_2eproto::InitDefaults();
  return *internal_default_instance();
}

DroneState* DroneState::New(::google::protobuf::Arena* arena) const {
  DroneState* n = new DroneState;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DroneState::Clear() {
// @@protoc_insertion_point(message_clear_start:DroneState)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&ip_, 0, reinterpret_cast<char*>(&curren_task_) -
    reinterpret_cast<char*>(&ip_) + sizeof(curren_task_));
}

bool DroneState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DroneState)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // fixed32 ip = 1;
      case 1: {
        if (tag == 13u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &ip_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 port = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 drone_id = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &drone_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 seq_num = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &seq_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 5;
      case 5: {
        if (tag == 42u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DroneState.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DroneState.CurrentTask curren_task = 6;
      case 6: {
        if (tag == 48u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_curren_task(static_cast< ::DroneState_CurrentTask >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DroneState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DroneState)
  return false;
#undef DO_
}

void DroneState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DroneState)
  // fixed32 ip = 1;
  if (this->ip() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->ip(), output);
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->port(), output);
  }

  // uint32 drone_id = 3;
  if (this->drone_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->drone_id(), output);
  }

  // int64 seq_num = 4;
  if (this->seq_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->seq_num(), output);
  }

  // string name = 5;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DroneState.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->name(), output);
  }

  // .DroneState.CurrentTask curren_task = 6;
  if (this->curren_task() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      6, this->curren_task(), output);
  }

  // @@protoc_insertion_point(serialize_end:DroneState)
}

::google::protobuf::uint8* DroneState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DroneState)
  // fixed32 ip = 1;
  if (this->ip() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->ip(), target);
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->port(), target);
  }

  // uint32 drone_id = 3;
  if (this->drone_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->drone_id(), target);
  }

  // int64 seq_num = 4;
  if (this->seq_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->seq_num(), target);
  }

  // string name = 5;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DroneState.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->name(), target);
  }

  // .DroneState.CurrentTask curren_task = 6;
  if (this->curren_task() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      6, this->curren_task(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DroneState)
  return target;
}

size_t DroneState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DroneState)
  size_t total_size = 0;

  // string name = 5;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // fixed32 ip = 1;
  if (this->ip() != 0) {
    total_size += 1 + 4;
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->port());
  }

  // int64 seq_num = 4;
  if (this->seq_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->seq_num());
  }

  // uint32 drone_id = 3;
  if (this->drone_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->drone_id());
  }

  // .DroneState.CurrentTask curren_task = 6;
  if (this->curren_task() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->curren_task());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DroneState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DroneState)
  GOOGLE_DCHECK_NE(&from, this);
  const DroneState* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DroneState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DroneState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DroneState)
    MergeFrom(*source);
  }
}

void DroneState::MergeFrom(const DroneState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DroneState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.ip() != 0) {
    set_ip(from.ip());
  }
  if (from.port() != 0) {
    set_port(from.port());
  }
  if (from.seq_num() != 0) {
    set_seq_num(from.seq_num());
  }
  if (from.drone_id() != 0) {
    set_drone_id(from.drone_id());
  }
  if (from.curren_task() != 0) {
    set_curren_task(from.curren_task());
  }
}

void DroneState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DroneState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DroneState::CopyFrom(const DroneState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DroneState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DroneState::IsInitialized() const {
  return true;
}

void DroneState::Swap(DroneState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DroneState::InternalSwap(DroneState* other) {
  name_.Swap(&other->name_);
  std::swap(ip_, other->ip_);
  std::swap(port_, other->port_);
  std::swap(seq_num_, other->seq_num_);
  std::swap(drone_id_, other->drone_id_);
  std::swap(curren_task_, other->curren_task_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DroneState::GetMetadata() const {
  protobuf_dronestate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_dronestate_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DroneState

// fixed32 ip = 1;
void DroneState::clear_ip() {
  ip_ = 0u;
}
::google::protobuf::uint32 DroneState::ip() const {
  // @@protoc_insertion_point(field_get:DroneState.ip)
  return ip_;
}
void DroneState::set_ip(::google::protobuf::uint32 value) {
  
  ip_ = value;
  // @@protoc_insertion_point(field_set:DroneState.ip)
}

// uint32 port = 2;
void DroneState::clear_port() {
  port_ = 0u;
}
::google::protobuf::uint32 DroneState::port() const {
  // @@protoc_insertion_point(field_get:DroneState.port)
  return port_;
}
void DroneState::set_port(::google::protobuf::uint32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:DroneState.port)
}

// uint32 drone_id = 3;
void DroneState::clear_drone_id() {
  drone_id_ = 0u;
}
::google::protobuf::uint32 DroneState::drone_id() const {
  // @@protoc_insertion_point(field_get:DroneState.drone_id)
  return drone_id_;
}
void DroneState::set_drone_id(::google::protobuf::uint32 value) {
  
  drone_id_ = value;
  // @@protoc_insertion_point(field_set:DroneState.drone_id)
}

// int64 seq_num = 4;
void DroneState::clear_seq_num() {
  seq_num_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 DroneState::seq_num() const {
  // @@protoc_insertion_point(field_get:DroneState.seq_num)
  return seq_num_;
}
void DroneState::set_seq_num(::google::protobuf::int64 value) {
  
  seq_num_ = value;
  // @@protoc_insertion_point(field_set:DroneState.seq_num)
}

// string name = 5;
void DroneState::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DroneState::name() const {
  // @@protoc_insertion_point(field_get:DroneState.name)
  return name_.GetNoArena();
}
void DroneState::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DroneState.name)
}
#if LANG_CXX11
void DroneState::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DroneState.name)
}
#endif
void DroneState::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DroneState.name)
}
void DroneState::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DroneState.name)
}
::std::string* DroneState::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:DroneState.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DroneState::release_name() {
  // @@protoc_insertion_point(field_release:DroneState.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DroneState::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DroneState.name)
}

// .DroneState.CurrentTask curren_task = 6;
void DroneState::clear_curren_task() {
  curren_task_ = 0;
}
::DroneState_CurrentTask DroneState::curren_task() const {
  // @@protoc_insertion_point(field_get:DroneState.curren_task)
  return static_cast< ::DroneState_CurrentTask >(curren_task_);
}
void DroneState::set_curren_task(::DroneState_CurrentTask value) {
  
  curren_task_ = value;
  // @@protoc_insertion_point(field_set:DroneState.curren_task)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
