// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class MessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Message>
      _instance;
} _Message_default_instance_;
namespace protobuf_message_2eproto {
void InitDefaultsMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_ping_2eproto::InitDefaultsPing();
  protobuf_shutdown_2eproto::InitDefaultsDoShutdown();
  protobuf_advertisement_2eproto::InitDefaultsAdvertisement();
  protobuf_hello_2eproto::InitDefaultsHello();
  protobuf_dronestate_2eproto::InitDefaultsDroneState();
  {
    void* ptr = &::_Message_default_instance_;
    new (ptr) ::Message();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::InitAsDefaultInstance();
}

void InitDefaultsMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMessageImpl);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message, ping_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message, shutdown_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message, advertisement_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message, hello_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message, dronestate_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Message)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Message_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "message.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rmessage.proto\032\nping.proto\032\016shutdown.pr"
      "oto\032\023advertisement.proto\032\013hello.proto\032\020d"
      "ronestate.proto\"\207\002\n\007Message\022\033\n\004type\030\001 \001("
      "\0162\r.Message.Type\022\023\n\004ping\030d \001(\0132\005.Ping\022\035\n"
      "\010shutdown\030e \001(\0132\013.DoShutdown\022%\n\radvertis"
      "ement\030f \001(\0132\016.Advertisement\022\025\n\005hello\030g \001"
      "(\0132\006.Hello\022\037\n\ndronestate\030h \001(\0132\013.DroneSt"
      "ate\"L\n\004Type\022\010\n\004PING\020\000\022\014\n\010SHUTDOWN\020\001\022\021\n\rA"
      "DVERTISEMENT\020\002\022\t\n\005HELLO\020\003\022\016\n\nDRONESTATE\020"
      "\004b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 369);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message.proto", &protobuf_RegisterTypes);
  ::protobuf_ping_2eproto::AddDescriptors();
  ::protobuf_shutdown_2eproto::AddDescriptors();
  ::protobuf_advertisement_2eproto::AddDescriptors();
  ::protobuf_hello_2eproto::AddDescriptors();
  ::protobuf_dronestate_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_message_2eproto
const ::google::protobuf::EnumDescriptor* Message_Type_descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_enum_descriptors[0];
}
bool Message_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Message_Type Message::PING;
const Message_Type Message::SHUTDOWN;
const Message_Type Message::ADVERTISEMENT;
const Message_Type Message::HELLO;
const Message_Type Message::DRONESTATE;
const Message_Type Message::Type_MIN;
const Message_Type Message::Type_MAX;
const int Message::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void Message::InitAsDefaultInstance() {
  ::_Message_default_instance_._instance.get_mutable()->ping_ = const_cast< ::Ping*>(
      ::Ping::internal_default_instance());
  ::_Message_default_instance_._instance.get_mutable()->shutdown_ = const_cast< ::DoShutdown*>(
      ::DoShutdown::internal_default_instance());
  ::_Message_default_instance_._instance.get_mutable()->advertisement_ = const_cast< ::Advertisement*>(
      ::Advertisement::internal_default_instance());
  ::_Message_default_instance_._instance.get_mutable()->hello_ = const_cast< ::Hello*>(
      ::Hello::internal_default_instance());
  ::_Message_default_instance_._instance.get_mutable()->dronestate_ = const_cast< ::DroneState*>(
      ::DroneState::internal_default_instance());
}
void Message::clear_ping() {
  if (GetArenaNoVirtual() == NULL && ping_ != NULL) {
    delete ping_;
  }
  ping_ = NULL;
}
void Message::clear_shutdown() {
  if (GetArenaNoVirtual() == NULL && shutdown_ != NULL) {
    delete shutdown_;
  }
  shutdown_ = NULL;
}
void Message::clear_advertisement() {
  if (GetArenaNoVirtual() == NULL && advertisement_ != NULL) {
    delete advertisement_;
  }
  advertisement_ = NULL;
}
void Message::clear_hello() {
  if (GetArenaNoVirtual() == NULL && hello_ != NULL) {
    delete hello_;
  }
  hello_ = NULL;
}
void Message::clear_dronestate() {
  if (GetArenaNoVirtual() == NULL && dronestate_ != NULL) {
    delete dronestate_;
  }
  dronestate_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Message::kTypeFieldNumber;
const int Message::kPingFieldNumber;
const int Message::kShutdownFieldNumber;
const int Message::kAdvertisementFieldNumber;
const int Message::kHelloFieldNumber;
const int Message::kDronestateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Message::Message()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_message_2eproto::InitDefaultsMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message)
}
Message::Message(const Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_ping()) {
    ping_ = new ::Ping(*from.ping_);
  } else {
    ping_ = NULL;
  }
  if (from.has_shutdown()) {
    shutdown_ = new ::DoShutdown(*from.shutdown_);
  } else {
    shutdown_ = NULL;
  }
  if (from.has_advertisement()) {
    advertisement_ = new ::Advertisement(*from.advertisement_);
  } else {
    advertisement_ = NULL;
  }
  if (from.has_hello()) {
    hello_ = new ::Hello(*from.hello_);
  } else {
    hello_ = NULL;
  }
  if (from.has_dronestate()) {
    dronestate_ = new ::DroneState(*from.dronestate_);
  } else {
    dronestate_ = NULL;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:Message)
}

void Message::SharedCtor() {
  ::memset(&ping_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&ping_)) + sizeof(type_));
  _cached_size_ = 0;
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:Message)
  SharedDtor();
}

void Message::SharedDtor() {
  if (this != internal_default_instance()) delete ping_;
  if (this != internal_default_instance()) delete shutdown_;
  if (this != internal_default_instance()) delete advertisement_;
  if (this != internal_default_instance()) delete hello_;
  if (this != internal_default_instance()) delete dronestate_;
}

void Message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Message::descriptor() {
  ::protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Message& Message::default_instance() {
  ::protobuf_message_2eproto::InitDefaultsMessage();
  return *internal_default_instance();
}


void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && ping_ != NULL) {
    delete ping_;
  }
  ping_ = NULL;
  if (GetArenaNoVirtual() == NULL && shutdown_ != NULL) {
    delete shutdown_;
  }
  shutdown_ = NULL;
  if (GetArenaNoVirtual() == NULL && advertisement_ != NULL) {
    delete advertisement_;
  }
  advertisement_ = NULL;
  if (GetArenaNoVirtual() == NULL && hello_ != NULL) {
    delete hello_;
  }
  hello_ = NULL;
  if (GetArenaNoVirtual() == NULL && dronestate_ != NULL) {
    delete dronestate_;
  }
  dronestate_ = NULL;
  type_ = 0;
  _internal_metadata_.Clear();
}

bool Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Message.Type type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::Message_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Ping ping = 100;
      case 100: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 802 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_ping()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DoShutdown shutdown = 101;
      case 101: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 810 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_shutdown()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Advertisement advertisement = 102;
      case 102: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 818 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_advertisement()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Hello hello = 103;
      case 103: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 826 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_hello()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DroneState dronestate = 104;
      case 104: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 834 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_dronestate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message)
  return false;
#undef DO_
}

void Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Message.Type type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .Ping ping = 100;
  if (this->has_ping()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      100, *ping_, output);
  }

  // .DoShutdown shutdown = 101;
  if (this->has_shutdown()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      101, *shutdown_, output);
  }

  // .Advertisement advertisement = 102;
  if (this->has_advertisement()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      102, *advertisement_, output);
  }

  // .Hello hello = 103;
  if (this->has_hello()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      103, *hello_, output);
  }

  // .DroneState dronestate = 104;
  if (this->has_dronestate()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      104, *dronestate_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message)
}

::google::protobuf::uint8* Message::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Message.Type type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .Ping ping = 100;
  if (this->has_ping()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        100, *ping_, deterministic, target);
  }

  // .DoShutdown shutdown = 101;
  if (this->has_shutdown()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        101, *shutdown_, deterministic, target);
  }

  // .Advertisement advertisement = 102;
  if (this->has_advertisement()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        102, *advertisement_, deterministic, target);
  }

  // .Hello hello = 103;
  if (this->has_hello()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        103, *hello_, deterministic, target);
  }

  // .DroneState dronestate = 104;
  if (this->has_dronestate()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        104, *dronestate_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Ping ping = 100;
  if (this->has_ping()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *ping_);
  }

  // .DoShutdown shutdown = 101;
  if (this->has_shutdown()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *shutdown_);
  }

  // .Advertisement advertisement = 102;
  if (this->has_advertisement()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *advertisement_);
  }

  // .Hello hello = 103;
  if (this->has_hello()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *hello_);
  }

  // .DroneState dronestate = 104;
  if (this->has_dronestate()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *dronestate_);
  }

  // .Message.Type type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Message* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Message>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message)
    MergeFrom(*source);
  }
}

void Message::MergeFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_ping()) {
    mutable_ping()->::Ping::MergeFrom(from.ping());
  }
  if (from.has_shutdown()) {
    mutable_shutdown()->::DoShutdown::MergeFrom(from.shutdown());
  }
  if (from.has_advertisement()) {
    mutable_advertisement()->::Advertisement::MergeFrom(from.advertisement());
  }
  if (from.has_hello()) {
    mutable_hello()->::Hello::MergeFrom(from.hello());
  }
  if (from.has_dronestate()) {
    mutable_dronestate()->::DroneState::MergeFrom(from.dronestate());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::Swap(Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Message::InternalSwap(Message* other) {
  using std::swap;
  swap(ping_, other->ping_);
  swap(shutdown_, other->shutdown_);
  swap(advertisement_, other->advertisement_);
  swap(hello_, other->hello_);
  swap(dronestate_, other->dronestate_);
  swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Message::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message* Arena::Create< ::Message >(Arena* arena) {
  return Arena::CreateInternal< ::Message >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
