// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

#ifndef PROTOBUF_ping_2eproto__INCLUDED
#define PROTOBUF_ping_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class Ping;
class PingDefaultTypeInternal;
extern PingDefaultTypeInternal _Ping_default_instance_;

namespace protobuf_ping_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ping_2eproto

enum Ping_PingType {
  Ping_PingType_REQUEST = 0,
  Ping_PingType_ACK = 1,
  Ping_PingType_Ping_PingType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Ping_PingType_Ping_PingType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Ping_PingType_IsValid(int value);
const Ping_PingType Ping_PingType_PingType_MIN = Ping_PingType_REQUEST;
const Ping_PingType Ping_PingType_PingType_MAX = Ping_PingType_ACK;
const int Ping_PingType_PingType_ARRAYSIZE = Ping_PingType_PingType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Ping_PingType_descriptor();
inline const ::std::string& Ping_PingType_Name(Ping_PingType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Ping_PingType_descriptor(), value);
}
inline bool Ping_PingType_Parse(
    const ::std::string& name, Ping_PingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Ping_PingType>(
    Ping_PingType_descriptor(), name, value);
}
// ===================================================================

class Ping : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Ping) */ {
 public:
  Ping();
  virtual ~Ping();

  Ping(const Ping& from);

  inline Ping& operator=(const Ping& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ping& default_instance();

  static inline const Ping* internal_default_instance() {
    return reinterpret_cast<const Ping*>(
               &_Ping_default_instance_);
  }

  void Swap(Ping* other);

  // implements Message ----------------------------------------------

  inline Ping* New() const PROTOBUF_FINAL { return New(NULL); }

  Ping* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Ping& from);
  void MergeFrom(const Ping& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Ping_PingType PingType;
  static const PingType REQUEST =
    Ping_PingType_REQUEST;
  static const PingType ACK =
    Ping_PingType_ACK;
  static inline bool PingType_IsValid(int value) {
    return Ping_PingType_IsValid(value);
  }
  static const PingType PingType_MIN =
    Ping_PingType_PingType_MIN;
  static const PingType PingType_MAX =
    Ping_PingType_PingType_MAX;
  static const int PingType_ARRAYSIZE =
    Ping_PingType_PingType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  PingType_descriptor() {
    return Ping_PingType_descriptor();
  }
  static inline const ::std::string& PingType_Name(PingType value) {
    return Ping_PingType_Name(value);
  }
  static inline bool PingType_Parse(const ::std::string& name,
      PingType* value) {
    return Ping_PingType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .Ping.PingType Type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Ping_PingType type() const;
  void set_type(::Ping_PingType value);

  // @@protoc_insertion_point(class_scope:Ping)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_ping_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Ping

// .Ping.PingType Type = 1;
inline void Ping::clear_type() {
  type_ = 0;
}
inline ::Ping_PingType Ping::type() const {
  // @@protoc_insertion_point(field_get:Ping.Type)
  return static_cast< ::Ping_PingType >(type_);
}
inline void Ping::set_type(::Ping_PingType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Ping.Type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Ping_PingType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Ping_PingType>() {
  return ::Ping_PingType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ping_2eproto__INCLUDED
