// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shutdown.proto

#ifndef PROTOBUF_shutdown_2eproto__INCLUDED
#define PROTOBUF_shutdown_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class DoShutdown;
class DoShutdownDefaultTypeInternal;
extern DoShutdownDefaultTypeInternal _DoShutdown_default_instance_;

namespace protobuf_shutdown_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_shutdown_2eproto

// ===================================================================

class DoShutdown : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DoShutdown) */ {
 public:
  DoShutdown();
  virtual ~DoShutdown();

  DoShutdown(const DoShutdown& from);

  inline DoShutdown& operator=(const DoShutdown& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DoShutdown& default_instance();

  static inline const DoShutdown* internal_default_instance() {
    return reinterpret_cast<const DoShutdown*>(
               &_DoShutdown_default_instance_);
  }

  void Swap(DoShutdown* other);

  // implements Message ----------------------------------------------

  inline DoShutdown* New() const PROTOBUF_FINAL { return New(NULL); }

  DoShutdown* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DoShutdown& from);
  void MergeFrom(const DoShutdown& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DoShutdown* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool force = 1;
  void clear_force();
  static const int kForceFieldNumber = 1;
  bool force() const;
  void set_force(bool value);

  // @@protoc_insertion_point(class_scope:DoShutdown)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool force_;
  mutable int _cached_size_;
  friend struct  protobuf_shutdown_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DoShutdown

// bool force = 1;
inline void DoShutdown::clear_force() {
  force_ = false;
}
inline bool DoShutdown::force() const {
  // @@protoc_insertion_point(field_get:DoShutdown.force)
  return force_;
}
inline void DoShutdown::set_force(bool value) {
  
  force_ = value;
  // @@protoc_insertion_point(field_set:DoShutdown.force)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_shutdown_2eproto__INCLUDED
